name: CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Docker pull image for tests
      run: docker pull perl:5.38.0

    - name: Build docker image for tests
      run: docker build . --file tests/Dockerfile.tsv2table_t --tag tsv2table_t:${{ github.sha }}

    - name: Run test in tests/
      run: >
        docker run
        --rm
        --volume=`pwd`/tsv2table:/app/tsv2table
        --volume=`pwd`/README.md:/app/README.md
        tsv2table_t:${{ github.sha }}
        prove -lvm tests/
