name: Relase

on:
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Add version information
      run: sed -i "s/VERSION = 'dev';/VERSION = '${{ github.ref_name }}';/" tsv2table

    - name: Create GitHub release
      run: gh release create ${{github.ref_name}} -t "Release ${{github.ref_name}}" tsv2table
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
