name: Relase

on:
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Prepare release and create GitHub release
      run: |
        gh release create ${{ github.ref }} -t "Release ${{ github.ref }}" -n "Release notes for ${{ github.ref }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

